dbt_learning_project:
  outputs:
    dev:
      account: ********
      database: DBT_TUTORIAL_DEV
      password: ********
      role: ACCOUNTADMIN
      schema: SOURCE
      threads: 4
      type: snowflake
      user: meetaghera
      warehouse: COMPUTE_WH
    prod:
      account: ********
      database: DBT_TUTORIAL_PROD
      password: ********
      role: ACCOUNTADMIN
      schema: SOURCE
      threads: 4
      type: snowflake
      user: meetaghera
      warehouse: COMPUTE_WH
  target: dev
